"""
Scaffolding helpers so host projects can consume Smart Token Prod via pip/git
instead of vendoring vendor/smart_token_prod/.

No network writes outside the target project path the caller passes.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Optional

DEFAULT_GIT_DEP = (
    "smart-token-prod @ "
    "git+https://github.com/dcpracmatic-prog/Smart-Token-Prod.git@v0.10.4"
)

BRIDGE_TEMPLATE = '''\
"""
Thin bridge — re-exports Smart Token Prod SDK for this project.

Generated by `smart-token integrate`. Prefer importing from here so the host
does not need PYTHONPATH=vendor hacks.

    from smart_token_bridge import protect_artifact, open_artifact, status
"""

from smart_token_prod.sdk import (  # noqa: F401
    artifact_friction_status,
    is_available,
    open_artifact,
    protect_artifact,
    repair_artifact_mac,
    status,
)

__all__ = [
    "is_available",
    "status",
    "protect_artifact",
    "open_artifact",
    "artifact_friction_status",
    "repair_artifact_mac",
]
'''

INTEGRATION_NOTES = """\
# Integración Smart Token Prod (generado)

Este archivo lo escribió `smart-token integrate`. Pasos recomendados:

## 1. Dependencia

Instala el paquete desde git (o editable local):

```bash
pip install "smart-token-prod @ git+https://github.com/dcpracmatic-prog/Smart-Token-Prod.git@v0.10.4"
# o editable:
# pip install -e /ruta/a/Smart-Token-Prod
```

Si el proyecto usa `requirements.txt`, la línea ya se añadió (o está en
`requirements-smart-token.txt`). Con solo `pyproject.toml`, revisa
`requirements-smart-token.txt` y añade la dependencia a tu `[project]` /
grupo de deps a mano (no se reescribe TOML a ciegas).

## 2. Quitar el vendor

Si existe `vendor/smart_token_prod/` (copia antigua / fork):

1. Elimina ese directorio del árbol y del control de versiones.
2. Deja de exportar `PYTHONPATH=vendor:.` (o equivalente) **solo** para STP.
3. Sustituye imports del estilo `from smart_token_prod import ...` que
   dependían del vendor por el bridge:

```python
from smart_token_bridge import (
    protect_artifact,
    open_artifact,
    artifact_friction_status,
    is_available,
    status,
)
```

O importa directo del paquete instalado:

```python
from smart_token_prod.sdk import protect_artifact, open_artifact, status
```

## 3. Comprobar

```bash
smart-token doctor
smart-token version
python -c "from smart_token_bridge import is_available; print(is_available())"
```

## 4. API de alto nivel

- `protect_artifact(path, master_secret=...)` → `(stok_path, key_path)`
- `open_artifact(stok, master_secret=..., key_path=...)` → `(bytes|None, info)`
- `artifact_friction_status(stok)` → dict de inspección
- `is_available()` / `status()` → salud del stack

Detalle: ver `docs/INTEGRATION.md` en el repo Smart-Token-Prod.
"""



def resolve_bridge_path(root: Path, relative_path: str) -> Path:
    """Resolve --bridge under project root; reject abs paths and .. escapes."""
    root = Path(root).resolve()
    rel = Path(relative_path)
    if rel.is_absolute():
        raise ValueError(
            f"bridge path must be relative to project root (got absolute: {relative_path})"
        )
    target = (root / rel).resolve()
    try:
        target.relative_to(root)
    except ValueError as exc:
        raise ValueError(
            f"bridge path escapes project root: {relative_path!r} → {target}"
        ) from exc
    return target


def detect_project(root: Path) -> Dict[str, Any]:
    """Detect project layout under root."""
    root = Path(root).resolve()
    pyproject = root / "pyproject.toml"
    requirements = root / "requirements.txt"
    vendor_stp = root / "vendor" / "smart_token_prod"

    paths: List[str] = []
    if pyproject.is_file():
        paths.append(str(pyproject))
    if requirements.is_file():
        paths.append(str(requirements))

    if requirements.is_file():
        kind = "requirements"
    elif pyproject.is_file():
        kind = "pyproject"
    else:
        kind = "unknown"

    return {
        "root": str(root),
        "kind": kind,
        "paths": paths,
        "has_pyproject": pyproject.is_file(),
        "has_requirements": requirements.is_file(),
        "vendor_stp_path": str(vendor_stp) if vendor_stp.exists() else None,
    }


def _git_dep_line() -> str:
    return DEFAULT_GIT_DEP


def _editable_dep_line(editable_path: Path) -> str:
    return f"-e {Path(editable_path).resolve()}"


def ensure_dependency(
    root: Path,
    mode: str = "git",
    editable_path: Optional[Path] = None,
    *,
    dry_run: bool = False,
) -> Dict[str, Any]:
    """
    Append dependency to requirements.txt, or write requirements-smart-token.txt
    when only pyproject.toml is present (do not mutate TOML blindly).
    """
    root = Path(root).resolve()
    if mode == "editable":
        if not editable_path:
            raise ValueError("editable_path required when mode='editable'")
        line = _editable_dep_line(Path(editable_path))
    else:
        line = _git_dep_line()

    req = root / "requirements.txt"
    hint = root / "requirements-smart-token.txt"
    written: List[str] = []
    action = "none"

    if req.is_file():
        text = req.read_text(encoding="utf-8")
        already = any(
            ln.strip() == line or "smart-token-prod" in ln
            for ln in text.splitlines()
        )
        if already:
            action = "skipped_already_present"
        else:
            action = "append_requirements"
            if not dry_run:
                sep = "" if text.endswith("\n") or not text else "\n"
                req.write_text(text + sep + line + "\n", encoding="utf-8")
            written.append(str(req))
    else:
        # pyproject-only or unknown: write hint file + note via INTEGRATION
        action = "write_hint_file"
        body = (
            "# Hint for Smart Token Prod — add this to your pyproject.toml\n"
            "# [project] dependencies, or: pip install -r requirements-smart-token.txt\n"
            f"{line}\n"
        )
        if not dry_run:
            hint.write_text(body, encoding="utf-8")
        written.append(str(hint))

    return {
        "mode": mode,
        "line": line,
        "action": action,
        "written": written,
        "dry_run": dry_run,
    }


def write_bridge_module(
    root: Path,
    relative_path: str = "smart_token_bridge.py",
    *,
    dry_run: bool = False,
) -> Dict[str, Any]:
    """Write thin re-export module under the host project."""
    root = Path(root).resolve()
    target = resolve_bridge_path(root, relative_path)
    rel_out = str(target.relative_to(root))
    if not dry_run:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(BRIDGE_TEMPLATE, encoding="utf-8")
    return {
        "path": str(target),
        "relative_path": rel_out,
        "dry_run": dry_run,
    }


def write_integration_notes(
    root: Path,
    *,
    dry_run: bool = False,
) -> Dict[str, Any]:
    """Write INTEGRATION.smart-token.md with migration steps."""
    root = Path(root).resolve()
    target = root / "INTEGRATION.smart-token.md"
    if not dry_run:
        target.write_text(INTEGRATION_NOTES, encoding="utf-8")
    return {"path": str(target), "dry_run": dry_run}


def run_integrate(
    root: Path,
    *,
    bridge_path: str = "smart_token_bridge.py",
    mode: str = "git",
    editable_path: Optional[Path] = None,
    dry_run: bool = False,
) -> Dict[str, Any]:
    """Detect project, ensure dep, write bridge + notes. Returns summary."""
    root = Path(root).resolve()
    if not root.is_dir():
        raise NotADirectoryError(f"PROJECT_DIR is not a directory: {root}")

    detected = detect_project(root)
    dep = ensure_dependency(
        root, mode=mode, editable_path=editable_path, dry_run=dry_run
    )
    bridge = write_bridge_module(root, relative_path=bridge_path, dry_run=dry_run)
    notes = write_integration_notes(root, dry_run=dry_run)

    # Extra short note when pyproject-only and we wrote the hint file
    extra_note: Optional[str] = None
    if detected["kind"] == "pyproject" and dep["action"] == "write_hint_file":
        extra = root / "INTEGRATION.generated.md"
        msg = (
            "# Smart Token — nota generada\n\n"
            "Se escribió `requirements-smart-token.txt` porque el proyecto "
            "usa `pyproject.toml` y no se reescribe TOML a ciegas.\n"
            "Copia la dependencia a `[project].dependencies` o instala con:\n\n"
            "```bash\npip install -r requirements-smart-token.txt\n```\n"
        )
        if not dry_run:
            extra.write_text(msg, encoding="utf-8")
        extra_note = str(extra)

    return {
        "root": str(root),
        "dry_run": dry_run,
        "detect": detected,
        "dependency": dep,
        "bridge": bridge,
        "notes": notes,
        "extra_note": extra_note,
        "vendor_stp_path": detected.get("vendor_stp_path"),
        "next_steps": [
            "pip install the printed dependency (or -r requirements-smart-token.txt)",
            "remove vendor/smart_token_prod/ if present",
            "stop using PYTHONPATH=vendor for Smart Token Prod",
            "import from smart_token_bridge or smart_token_prod.sdk",
            "run: smart-token doctor",
        ],
    }


def print_dep_lines(editable_path: Optional[Path] = None) -> List[str]:
    """Return pip install line(s) for CLI print-dep."""
    if editable_path is not None:
        return [f"pip install {_editable_dep_line(Path(editable_path))}"]
    return [f'pip install "{_git_dep_line()}"']
